import uuid
from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Any

from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from sonora.db.base import Base, Timestamps
from sonora.db.types import JSONType
from sonora.models._enum import enum_column

if TYPE_CHECKING:
    from sonora.models.training_session import TrainingSession


class AnalysisStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    READY = "ready"
    FAILED = "failed"


class SessionAnalysis(Timestamps, Base):
    """Lecture analysis (scores, topic timing) of one session; only its owner can see it.

    Generated by its own background job after the session is ready, so a slow or failed
    analysis never holds back the script and quiz.
    """

    __tablename__ = "session_analyses"

    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("training_sessions.id", ondelete="CASCADE"), primary_key=True
    )
    # Declared for flush ordering (parent rows insert first); never lazy-loaded.
    session: Mapped["TrainingSession"] = relationship(lazy="raise")
    status: Mapped[AnalysisStatus] = mapped_column(enum_column(AnalysisStatus, 16))
    # {"scores": {...}, "topics": [...], "metrics": {...}}, see sonora.ai.analysis.
    result: Mapped[dict[str, Any] | None] = mapped_column(JSONType)
    # The LLM that produced the result.
    model: Mapped[str | None] = mapped_column(String(100))
    # User-facing reason for status=failed (never raw exception text).
    error_message: Mapped[str | None] = mapped_column(String(300))
    completed_at: Mapped[datetime | None]
