import { act, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { api } from "../api.js";
import AnalysisView from "../components/AnalysisView.jsx";
import { BarRow, RadarChart } from "../components/charts.jsx";

const READY = {
  status: "ready",
  error_message: null,
  model: "qwen3.5:9b",
  completed_at: "2026-10-04T10:00:00Z",
  scores: {
    content: { score: 8, assessment: "Clear explanations.", tip: "Add a summary slide." },
    rhetoric: { score: 6, assessment: "Many filler words.", tip: "" },
    structure: { score: 7, assessment: "Logical order.", tip: "Announce the agenda." },
  },
  topics: [
    { title: "Welcome", start_seconds: 3, end_seconds: 123, duration_seconds: 120 },
    { title: "Immunity basics", start_seconds: 123, end_seconds: 483, duration_seconds: 360 },
    { title: "Wrap-up", start_seconds: 483, end_seconds: 603, duration_seconds: 120 },
  ],
  metrics: { words: 1500, words_per_minute: 150 },
};

afterEach(() => vi.useRealTimers());

describe("AnalysisView", () => {
  it("shows the scores on a radar chart with their reasons and the time per topic", async () => {
    vi.spyOn(api, "analysis").mockResolvedValue(READY);
    render(<AnalysisView sessionId="s1" />);

    const chart = await screen.findByRole("img", { name: /Lecture scores/ });
    expect(chart.getAttribute("aria-label")).toBe(
      "Lecture scores: Content 8 of 10, Rhetoric 6 of 10, Structure 7 of 10",
    );
    expect(screen.getByText("Many filler words.")).toBeTruthy();
    expect(screen.getByText("150")).toBeTruthy(); // words per minute
    // The tips are collected next to the chart, labelled with their category; empty ones are left out.
    const next = screen.getByText("Try next time").closest(".analysis-next");
    expect([...next.querySelectorAll(".analysis-next-label")].map((l) => l.textContent)).toEqual(["Content", "Structure"]);
    expect(next.textContent).toContain("Announce the agenda.");
    // The assessments sit in three equal cards below.
    expect(document.querySelectorAll(".analysis-cards > .analysis-card")).toHaveLength(3);
    expect(screen.getByText("6 min · 60%")).toBeTruthy();
    expect(screen.getByText("10 min in total")).toBeTruthy();
    expect(screen.queryByText(/Generated by/)).toBeNull(); // no model line under the analysis
    expect(screen.getByText(/assessed by AI from the transcript/)).toBeTruthy();
  });

  it("offers to analyse sessions from before the feature and polls until it is ready", async () => {
    vi.useFakeTimers({ shouldAdvanceTime: true });
    const load = vi
      .spyOn(api, "analysis")
      .mockResolvedValueOnce({ status: "none" })
      .mockResolvedValueOnce({ status: "running" })
      .mockResolvedValue(READY);
    const request = vi.spyOn(api, "requestAnalysis").mockResolvedValue({ status: "queued" });
    render(<AnalysisView sessionId="s1" />);

    fireEvent.click(await screen.findByRole("button", { name: /Analyze lecture/ }));
    expect(await screen.findByText("Analyzing the lecture…")).toBeTruthy();
    expect(request).toHaveBeenCalledWith("s1");

    await act(() => vi.advanceTimersByTimeAsync(4000));
    expect(screen.getByText("Analyzing the lecture…")).toBeTruthy();
    await act(() => vi.advanceTimersByTimeAsync(4000));
    expect(await screen.findByRole("img", { name: /Lecture scores/ })).toBeTruthy();
    expect(load).toHaveBeenCalledTimes(3);
  });

  it("explains a failed analysis and can retry it", async () => {
    vi.spyOn(api, "analysis").mockResolvedValue({ status: "failed", error_message: "The analysis could not be created." });
    const request = vi.spyOn(api, "requestAnalysis").mockResolvedValue({ status: "queued" });
    render(<AnalysisView sessionId="s1" />);

    expect(await screen.findByText("The analysis could not be created.")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: /Try again/ }));
    expect(await screen.findByText("Analyzing the lecture…")).toBeTruthy();
    expect(request).toHaveBeenCalledOnce();
  });

  it("reports errors from the server", async () => {
    vi.spyOn(api, "analysis").mockResolvedValue({ status: "none" });
    vi.spyOn(api, "requestAnalysis").mockRejectedValue(new Error("Too many analysis requests."));
    render(<AnalysisView sessionId="s1" />);
    fireEvent.click(await screen.findByRole("button", { name: /Analyze lecture/ }));
    expect((await screen.findByRole("alert")).textContent).toContain("Too many analysis requests.");
  });

  it("shows load failures", async () => {
    vi.spyOn(api, "analysis").mockRejectedValue(new Error("Session not found."));
    render(<AnalysisView sessionId="s1" />);
    expect((await screen.findByRole("alert")).textContent).toContain("Session not found.");
  });

  it("leaves out the pace for very short recordings", async () => {
    vi.spyOn(api, "analysis").mockResolvedValue({ ...READY, metrics: { words: 20, words_per_minute: null } });
    render(<AnalysisView sessionId="s1" />);
    await screen.findByRole("img", { name: /Lecture scores/ });
    expect(screen.queryByText(/Speaking pace/)).toBeNull();
  });
});

describe("charts", () => {
  const AXES = [
    { key: "a", label: "Content", value: 8 },
    { key: "b", label: "Rhetoric", value: 4 },
    { key: "c", label: "Structure", value: 10 },
  ];

  it("labels every axis with its value and shows a tooltip on focus and hover", () => {
    render(<RadarChart axes={AXES} title="Scores" />);
    expect(screen.getByText("8/10")).toBeTruthy();
    const rhetoric = screen.getByRole("img").querySelector('[aria-label="Rhetoric: 4 of 10"]');

    fireEvent.focus(rhetoric);
    expect(screen.getByRole("status").textContent).toBe("4 / 10Rhetoric");
    fireEvent.blur(rhetoric);
    expect(screen.queryByRole("status")).toBeNull();

    fireEvent.pointerEnter(rhetoric);
    expect(screen.getByRole("status")).toBeTruthy();
    fireEvent.pointerLeave(rhetoric);
    expect(screen.queryByRole("status")).toBeNull();
  });

  it("draws the score polygon inside the scale", () => {
    const { container } = render(<RadarChart axes={AXES} title="Scores" />);
    const area = container.querySelector(".radar-area").getAttribute("points").split(" ");
    expect(area).toHaveLength(3);
    // 10/10 on the third axis reaches the outer ring (radius 100 around 160,160).
    const [x, y] = area[2].split(",").map(Number);
    expect(Math.hypot(x - 160, y - 160)).toBeCloseTo(100, 5);
  });

  it("keeps the label of the top axis clear of the outer ring", () => {
    const { container } = render(<RadarChart axes={AXES} title="Scores" />);
    const top = [...container.querySelectorAll(".radar-label")].find((t) => t.textContent.startsWith("Content"));
    const valueBaseline = Number(top.getAttribute("y")) + 15; // second line
    expect(valueBaseline).toBeLessThan(160 - 100 - 4); // outer ring top, minus a margin
    const side = [...container.querySelectorAll(".radar-label")].find((t) => t.textContent.startsWith("Rhetoric"));
    expect(Number(side.getAttribute("y"))).toBeGreaterThan(160); // lower labels stay beside their axis
  });

  it("draws no mark for zero", () => {
    const { container } = render(<BarRow label="A" value={0} max={5} display="0%" />);
    expect(container.querySelector(".bar-fill").className).toContain("zero");
  });

  it("sizes bars relative to the maximum and keeps them in range", () => {
    const { container, rerender } = render(<BarRow label="A" value={3} max={4} display="75%" />);
    expect(container.querySelector(".bar-fill").style.width).toBe("75%");
    rerender(<BarRow label="A" value={5} max={0} display="0%" tone="muted" />);
    expect(container.querySelector(".bar-fill").style.width).toBe("0%");
    expect(container.querySelector(".bar-row").className).toContain("muted");
  });
});
